### REST Client for Visual Studio Code "ext install humao.rest-client" ###

@baseUrl = http://localhost:3333/transactions

### List transactions
GET {{baseUrl}}

### Get summary
GET {{baseUrl}}/summary

### List transaction by id
GET {{baseUrl}}/09a8767f-854c-42ea-83c7-9108ebdc8e76

### Create transaction
POST {{baseUrl}}
Content-Type: application/json

{
  "title":"Salário",
  "amount": 100,
  "type": "credit"
}

### Authenticate
# @name authenticated
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "brunosdua@dev.bru",
  "password": "123456"
}

### you need authenticate to obtain token
@token = {{authenticated.response.body.token}}

### Profile
GET {{baseUrl}}/transactions HTTP/1.1
Authorization: Bearer {{token}}

### Refresh token
PATCH {{baseUrl}}/token/refresh
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "brunosd@dev.br",
  "password": "123456"
}

### Create gym
POST {{baseUrl}}/gyms
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "TypeScript Gym",
  "description": "Some description.",
  "phone": "1199999999",
  "latitude": -27.2092052,
  "longitude": -49.6401091,
}


